# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be1cca26798afa31df7aa064a2809c60ff4a21761387d0d92feb7c5e99e55eaeed654d8d1ab1b4458f72cf70b3c6d31ef03f6e47d339e28088dd6a5b3876b236

test:
  secret_key_base: 48c58d12be911390cafb754b5d88233e9d12b1a5461be274f7b26160555f3bbbf50fe25a6f0c53dc5fd4d645aa70174f90209f2610f446e2c297b911ecaca492

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_token: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
